project:
  type: book
  output-dir: docs

execute:
  freeze: auto  # re-render only when source changes
  
editor: visual
book: 
  title: Stat 801A Notes
  
  chapters:
    - index.qmd
    - Section 1 Introduction.qmd
    - Section 2 Probability.qmd
    - Section 3 Sampling Distributions.qmd
    - Section4-One-Pred-Two-Levels.qmd
    - Section5-One-Pred-More-Than-Two-Levels.qmd
   
  downloads: [pdf]    


format: 
  html: default
  pdf:  
    header-includes:
      - \usepackage{float}
      - \floatplacement{table}{H}  
    output-file: pdf-book
    fontsize: 11pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm
   