project:
  type: book
  output-dir: docs


editor: visual
book: 
  title: Stat 801A Notes
  
  chapters:
    - index.qmd
    - Section 1 Introduction.qmd
    - Section 2 Probability.qmd
    - Section 3 Sampling Distributions.qmd
    - Section 4 One Pred Two Levels.qmd
   
  downloads: [pdf]    
format: 
  html: default
  pdf:  
    header-includes:
      - \usepackage{float}
      - \floatplacement{table}{H}  
    output-file: pdf-book
    fontsize: 11pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm
      
